# Generated by CMake, DO NOT EDIT

empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/qinyuhang/GitHub/shadowsocks-libev/libipset/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/qinyuhang/GitHub/shadowsocks-libev/libipset/cmake/FindCTargets.cmake))

/Users/qinyuhang/GitHub/shadowsocks-libev/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.7.2/bin/cmake -H/Users/qinyuhang/GitHub/shadowsocks-libev -B/Users/qinyuhang/GitHub/shadowsocks-libev
